### ISSUE TITLE
Cannot find module 'tree-kill'

### ISSUE THREAD

**Issue by DomVinyard** [yacut/brackets-nodejs-integration#12]
I cannot start any process without hitting these errors:

Command: node  --debug-brk=61690   "/Users/user/Library/Application Support/Brackets/extensions/user/brackets-nodejs-integration/tests/hello.js" 
Working directory: /Users/user/Dev/project/
Error occured: 
Unable to load one of the modules: /Users/user/Library/Application Support/Brackets/extensions/user/brackets-nodejs-integration/src/domains/3aec8c33-b844-dfbb-7531-055802173ed6, reason: Cannot find module 'tree-kill'

**Comment by JonLambell** [comment]
Same issue here.

**Comment by yacut** [comment]
fixed with 1.8.8.
