### ISSUE TITLE
node.js brackets

### ISSUE THREAD

**Issue by seriiserii825** [yacut/brackets-nodejs-integration#13]
Подскажи пожалуйста, как настроить работу node.js в brackets. Я новичок и у меня не получается. По твоим скриншотам у меня не получается, выдает ошибку:

Command: node   "/home/serii/Рабочий стол/test/script.js" 
Working directory: /home/serii/Рабочий стол/test/
/bin/sh: 1: node: not found
Program exited with code 127
![2016-08-25 00 24 56](https://cloud.githubusercontent.com/assets/20783270/17948689/8c0d68f6-6a5a-11e6-8501-8677d7786067.png)

**Comment by mintjava** [comment]
Iam also getting the same error Is there any patch for this error.

**Comment by twosouth** [comment]
I am having  the same issue when the extension attempts to start its own samples: process sample and the http server sample.

I get this:

Command: node   "/Users/sssss/Library/Application Support/Brackets/extensions/user/brackets-nodejs-integration/tests/hello.js" 
/bin/sh: node: command not found
Program exited with code 127

node is installed globally 
I am at node v6.5.0

Nothing on google was helpful.

**Comment by luiskrieg** [comment]
Hi guys, 

I find the way how to fix it on MacOS Sierra, I think should be the same on WinOS or LinuxOS.

1. Open settings
2. Add the node.exe path, on MacOS is: /usr/local/bin/node
3. On target folder, add your project location
4. Save and run

![captura de pantalla 2016-09-30 a la s 13 45 31](https://cloud.githubusercontent.com/assets/18009526/19002960/331daa5e-8714-11e6-9ea2-f17bb5f40581.png)

I hope this help. 

Saludos desde México.
KriegWar->LRGA

**Comment by yacut** [comment]
Thanks @luiskrieg. Closed.
