### ISSUE TITLE
"See Difference" fails for strings

### ISSUE THREAD

**Issue by jws121295** [yacut/brackets-nodejs-integration#2]
When an AssersionError occurs as a result of a mismatched string, a TypeError in Brackets is thrown here:
> objectDiff.js:100 `var keys = Object.keys(a);`

Because in this instance, _a_ is not an object, but a string.

This test should reproduce the error:
`expect("stringA").to.equal("stringB");`

**Comment by yacut** [comment]
Thanks you for this issue. The Problem was fixed with 1.2.0 release.
