### ISSUE TITLE
Start current NodeJS project with command+shift+P doesn't run.

### ISSUE THREAD

**Issue by rathapolk** [yacut/brackets-nodejs-integration#25]
I have run the 'Start (current NodeJS project)'  with the shortcut command+shift+P on Mac. It showed a blank tab. But when I clicked on the menu, it did show a tab with the project running correctly.  

Tested in version 1.8.9.

**Comment by yacut** [comment]
I can't reproduce this issue. Could you please show the errors in the developer tools (F12) console and post it hier?

**Comment by rathapolk** [comment]
It happens when I hit the shortcut keys (command+shift+P) while there is no NodeJS tab at all.


Below is the message in the developer tools. 

`Uncaught TypeError: Cannot read property 'match' of undefined    keywords_parser.js:36`
`exports.parse	@	keywords_parser.js:36`
`change_run_configuration	@	runner_panel.js:407`
`(anonymous function)	@	runner_panel.js:260`
`n.event.dispatch	@	thirdparty.min.js:20`
`r.handle	@	thirdparty.min.js:20`
`n.event.trigger	@	thirdparty.min.js:20`
`(anonymous function)	@	thirdparty.min.js:20`
`n.extend.each	@	thirdparty.min.js:19`
`n.fn.n.each	@	thirdparty.min.js:19`
`n.fn.extend.trigger	@	thirdparty.min.js:20`
`create_new_tab_if_config_is_set_and_panel_empty	@	runner_panel.js:576`
`panel.show	@	runner_panel.js:64`
`create_and_run_configuration	@	main.js:140`
`(anonymous function)	@	main.js:117`
`Command.execute	@	/command/CommandManager.js:93`
`execute	@	/command/CommandManager.js:287`
`executeCommand	@	/utils/ShellAPI.js:62`

**Comment by yacut** [comment]
The v1.8.10 release should fix this issue. Please check.

**Comment by rathapolk** [comment]
Yes. the v1.8.10 does fix this issue.
