### ISSUE TITLE
Error installing in other langage

### ISSUE THREAD

**Issue by erathostene** [yacut/brackets-nodejs-integration#26]
Hi,
My default system langage isn't english and when installing nodeJS-integration it crashes : 

`GET [..]/user/brackets-nodejs-integration-1.8.9/nls/fr/strings.js :NOT FOUND`
`[Extension] failed to load [..]/user/brackets-nodejs-integration-1.8.9 -Error : Load timeout for modules : i18n!nls/strings_unnormalized6,i18n!nls/strings`

So i changed my default langage to english but he same error occurs (trying to get a `eng-gb` directory this time) . Trying to rename the "root" directory didn't fix it as well (error trying to find the "root" directory...)

**Comment by yacut** [comment]
Please check v1.8.10
