### ISSUE TITLE
Cannot find module 'tree-kill'

### ISSUE THREAD

**Issue by zalgocykel** [yacut/brackets-nodejs-integration#30]
I've tested this extension and it worked nice with my gulpfile. But when I was going to use it now it suddenly throws an error 
`Unable to load one of the modules: C:/Users/*****/AppData/Roaming/Brackets/extensions/user/brackets-nodejs-integration/src/domains/b5ce95f6-ef42-bcf8-9274-8178e81796dd, reason: Cannot find module 'tree-kill`

I tried to install the modules with npm install in the brackets-nodejs-integration folder but it didn't help.

**Comment by yacut** [comment]
Please use npm registry to install extension: https://github.com/yacut/brackets-nodejs-integration#extension-installation

**Comment by Gal0n** [comment]
After installing by npm registry `Cannot find module 'tree-kill' ` error has left. But extension doesn't work. I'm trying to execute `gulp default` but I get an error (see screenshot below) and gulp.js file automatically opened on my desktop.
![pic](https://cloud.githubusercontent.com/assets/6124567/23181043/78dad062-f884-11e6-8d75-93dbf15a434d.jpg)

Everything worked fine before update.

**Comment by zalgocykel** [comment]
Yeah I think it broke after the update

**Comment by yacut** [comment]
These are two problems here:

1. The command "npm install" fails during installation. The solution: reinstall extension via "npm registry" or run "npm install" manually in extension directory.
2.  The gulp.js file opens on the desktop instead of run the gulp command. I guess this happens with windows users. The solution: up to version 1.8.17 you can set gulp binary path or leave it empty to use global binary.

**Comment by Gal0n** [comment]
@yacut Thanks. It's work.

You're right. After installation of version 1.8.7 gulp and mocha binary paths were C:/Users/*****/AppData/Roaming/Brackets/extensions/user/brackets-nodejs-integration/node_modules/gulp/bin/gulp.js.
I set it empty and all works fine.

**Comment by zalgocykel** [comment]
@yacut 
Thanks man it works for me to now!

**Comment by yacut** [comment]
No problem.

**Comment by Andrey7287** [comment]
So, I still don`t understand how to fix this issue !? 

Yes, I can run npm install manualy, I can run manualy other scripts, also.  But i used to this extension for this , and have no reson use it now because it DOESN`T RUN any scripts from my npm file !

Previouse version worked FINE !
