### ISSUE TITLE
Contribution pt-br

### ISSUE THREAD

**Issue by nelson777** [yacut/brackets-nodejs-integration#31]
Hello, I would like to contribute the translation to pt-br. I already made it. How can I send it to you ?

I cloned the project. If you just include me in the contributors list, I can just push the changes to the project. 

It's just 2 files. A modificated main string.js in which I included pt-br as language, and a strings.js translated to portuguese that I put in a pt-br folder.

**Comment by yacut** [comment]
Could you please create a pull request?
https://help.github.com/articles/creating-a-pull-request/#creating-the-pull-request

**Comment by nelson777** [comment]
Yes, but I'm not familiar with the process. Which branch should I clone and push the commits to ? develop ?

**Comment by nelson777** [comment]
I cloned master branch and then tried to create a branch on local repository and push it with this command:

    git push origin pt-br-translation

but got the following message:

    remote: Permission to yacut/brackets-nodejs-integration.git denied to nelson777.
    fatal: unable to access 'https://nelson777%40gmail.com:Github7.7.7@github.com/yacut/brackets-nodejs-integration.git/': The requested URL returned error: 403

**Comment by nelson777** [comment]
Created it. Please review.

**Comment by yacut** [comment]
https://github.com/yacut/brackets-nodejs-integration/pull/32 was merged.

**Comment by nelson777** [comment]
nice :) thanks
