### ISSUE TITLE
Running the current file/project with Node?

### ISSUE THREAD

**Issue by xingped** [yacut/brackets-nodejs-integration#6]
I know in the settings you can add "profiles" to run a specific target file. However, is there some way to say "run the current file/project"?

**Comment by yacut** [comment]
Thank you for the Idea. I think "run the current project" command is not necessary, but "run the current file" would be helpful. I will implement this in future releases.

**Comment by yacut** [comment]
The feature is available with 1.6.0 release.

**Comment by xingped** [comment]
Thanks! Love the "run current file" option now available! For the "run current project" you could look at if there is a package.json file and execute the "main" file that is given.

i.e. your package.json might look like this: 
`{
    "main": "app.js",
    "dependencies": { ... }
}`

And it would run app.js. Would be very helpful for multi-file projects.

"main" is a valid package.json property for Node. If I do `node .` in my code directory, it will execute the file defined in the "main" property.

**Comment by yacut** [comment]
'Start current nodejs project' feature is available now with 1.7.1 release.

**Comment by xingped** [comment]
Thanks! You're awesome! Also thanks for the font fix!
