### ISSUE TITLE
Is compatible with electron-mocha/electron

### ISSUE THREAD

**Issue by brianmaher84** [yacut/brackets-nodejs-integration#7]
I'm using electron-mocha and just wanted to let you know this works fine for me on OSX to run the mocha tests in brackets.

Just required to set the path to mocha to:
/usr/local/bin/electron-mocha

This isn't really an issue but couldn't see another way to let you know it works 👍 

The wiki button isn't working for me.

**Comment by yacut** [comment]
Thank you for the feedback. I'll added it to the wiki pages.

**Comment by yacut** [comment]
Done ;)
https://github.com/yacut/brackets-nodejs-integration/wiki/Advanced-Settings
